
drop role appdba;
create role appdba;

-- System Privileges    ROLE

grant ADMINISTER DATABASE TRIGGER        to APPDBA;
grant ADMINISTER RESOURCE MANAGER        to APPDBA;
grant ALTER USER to APPDBA;
grant ALTER ANY CLUSTER  to APPDBA;
grant ALTER ANY DIMENSION        to APPDBA;
grant ALTER ANY INDEX    to APPDBA;
grant ALTER ANY INDEXTYPE        to APPDBA;
grant ALTER ANY LIBRARY  to APPDBA;
grant ALTER ANY OUTLINE  to APPDBA;
grant ALTER ANY PROCEDURE        to APPDBA;
grant ALTER ANY SEQUENCE         to APPDBA;
grant ALTER ANY TABLE    to APPDBA;
grant ALTER ANY TRIGGER  to APPDBA;
grant ALTER ANY TYPE     to APPDBA;
grant ALTER DATABASE     to APPDBA;
grant ALTER SESSION      to APPDBA;
-- Removed per SCAN request 33687, V.Salerno 11/3/16
--grant ALTER SYSTEM       to APPDBA;
grant ALTER TABLESPACE   to APPDBA;
grant ANALYZE ANY        to APPDBA;
grant AUDIT ANY  to APPDBA;
grant BACKUP ANY TABLE   to APPDBA;
grant COMMENT ANY TABLE  to APPDBA;
grant CREATE ANY CLUSTER         to APPDBA;
grant CREATE ANY CONTEXT         to APPDBA;
grant CREATE ANY DIMENSION       to APPDBA;
grant CREATE ANY DIRECTORY       to APPDBA;
grant CREATE ANY INDEX   to APPDBA;
grant CREATE ANY INDEXTYPE       to APPDBA;
grant CREATE ANY LIBRARY         to APPDBA;
grant CREATE ANY OPERATOR        to APPDBA;
grant CREATE ANY PROCEDURE       to APPDBA;
grant CREATE ANY SEQUENCE        to APPDBA;
grant CREATE ANY SNAPSHOT        to APPDBA;
grant CREATE ANY SYNONYM         to APPDBA;
grant CREATE ANY TABLE   to APPDBA;
grant CREATE ANY TRIGGER         to APPDBA;
grant CREATE ANY TYPE    to APPDBA;
grant CREATE ANY VIEW    to APPDBA;
grant CREATE CLUSTER     to APPDBA;
grant CREATE DATABASE LINK       to APPDBA;
grant CREATE INDEXTYPE   to APPDBA;
grant CREATE PROCEDURE   to APPDBA;
grant CREATE PROFILE     to APPDBA;
grant CREATE PUBLIC DATABASE LINK        to APPDBA;
grant CREATE PUBLIC SYNONYM      to APPDBA;
grant CREATE SEQUENCE    to APPDBA;
grant CREATE SESSION     to APPDBA;
grant CREATE SYNONYM     to APPDBA;
grant CREATE TABLE       to APPDBA;
grant CREATE TABLESPACE  to APPDBA;
grant CREATE TRIGGER     to APPDBA;
grant CREATE USER        to APPDBA;
grant CREATE VIEW        to APPDBA;
grant DELETE ANY TABLE   to APPDBA;
grant DEQUEUE ANY QUEUE  to APPDBA;
grant DROP ANY CLUSTER   to APPDBA;
grant DROP ANY CONTEXT   to APPDBA;
grant DROP ANY DIMENSION         to APPDBA;
grant DROP ANY DIRECTORY         to APPDBA;
grant DROP ANY INDEX     to APPDBA;
grant DROP ANY INDEXTYPE         to APPDBA;
grant DROP ANY PROCEDURE         to APPDBA;
grant DROP ANY SEQUENCE  to APPDBA;
grant DROP ANY SYNONYM   to APPDBA;
grant DROP ANY TABLE     to APPDBA;
grant DROP ANY TRIGGER   to APPDBA;
grant DROP ANY VIEW      to APPDBA;
grant DROP PROFILE       to APPDBA;
grant DROP PUBLIC DATABASE LINK  to APPDBA;
grant DROP PUBLIC SYNONYM        to APPDBA;
grant DROP TABLESPACE    to APPDBA;
grant DROP USER  to APPDBA;
grant ENQUEUE ANY QUEUE  to APPDBA;
grant EXECUTE ANY INDEXTYPE      to APPDBA;
grant EXECUTE ANY PROCEDURE      to APPDBA;
grant EXECUTE ANY TYPE   to APPDBA;
grant FORCE ANY TRANSACTION      to APPDBA;
grant FORCE TRANSACTION  to APPDBA;
grant GLOBAL QUERY REWRITE       to APPDBA;
grant INSERT ANY TABLE   to APPDBA;
grant LOCK ANY TABLE     to APPDBA;
grant MANAGE ANY QUEUE   to APPDBA;
grant MANAGE TABLESPACE  to APPDBA;
grant RESTRICTED SESSION         to APPDBA;
grant SELECT ANY TABLE   to APPDBA;
grant SELECT ANY DICTIONARY      to APPDBA;
grant UPDATE ANY TABLE   to APPDBA;
grant CREATE ROLE to APPDBA;
grant ALTER ANY ROLE to APPDBA;
grant DROP ANY ROLE to APPDBA;

-----2006/02/22 - gsmith - added these lines for password expiration routines
GRANT SELECT   ON  "SYS"."DBA_PROFILES" TO "APPDBA" ;
GRANT SELECT   ON  "SYS"."DBA_USERS" TO "APPDBA" ;
GRANT SELECT ON  "SYS"."USER$" TO "APPDBA" ;

-----2007/04/17 - gsmith - added these lines for auditing monitoring
GRANT SELECT   ON  "SYS"."AUD$" TO "APPDBA" ;
-----2008/07/16 - gsmith - added 
GRANT SELECT 
    ON  "SYS"."V_$DATABASE" TO "APPDBA" ;

GRANT exp_full_database, imp_full_database  TO APPDBA;

-----2014/09/17 adding for awr reportins - RAB
GRANT SELECT ON SYS.V_$DATABASE TO APPDBA;
GRANT SELECT ON SYS.V_$INSTANCE TO APPDBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO APPDBA;
GRANT SELECT ON SYS.DBA_HIST_DATABASE_INSTANCE TO APPDBA;
GRANT SELECT ON SYS.DBA_HIST_SNAPSHOT TO APPDBA;
GRANT OEM_ADVISOR to APPDBA;
GRANT ADVISOR to APPDBA;

GRANT EXECUTE ON SYS.DBMS_EXPORT_EXTENSION TO APPDBA;

