drop user imperva cascade;
drop role assessment_role;
create user imperva identified by "changeAf!er8reation" profile VERIFY_PW_LOCKED password expire;
create role assessment_role;
grant assessment_role to imperva;
grant create session to assessment_role;
grant select on sys.registry$history to assessment_role;
grant select on sys.dba_db_links to assessment_role;
grant select on sys.dba_objects to assessment_role;
grant select on sys.dba_priv_audit_opts to assessment_role;
grant select on sys.dba_profiles to assessment_role;
grant select on sys.dba_role_privs to assessment_role;
grant select on sys.dba_roles to assessment_role;
grant select on sys.dba_scheduler_jobs to assessment_role;
grant select on sys.dba_stmt_audit_opts to assessment_role;
grant select on sys.dba_sys_privs to assessment_role;
grant select on sys.dba_tab_privs to assessment_role;
grant select on sys.dba_users to assessment_role;
grant select on sys.link$ to assessment_role;
grant select on sys.profile$ to assessment_role;
grant select on sys.profname$ to assessment_role;
grant select on sys.resource_map to assessment_role;
grant select on sys.role_tab_privs to assessment_role;
grant select on sys.sysauth$ to assessment_role;
grant select on sys.user$ to assessment_role;
grant select on sys.v_$controlfile to assessment_role;
grant select on sys.v_$database to assessment_role;
grant select on sys.v_$datafile to assessment_role;
grant select on sys.v_$logfile to assessment_role;
grant select on sys.v_$parameter to assessment_role;
grant select on sys.v_$pwfile_users to assessment_role;
grant select on sys.dba_data_files to assessment_role;
grant select on sys.dba_external_tables to assessment_role;
grant select on sys.dba_jobs to assessment_role;
grant select on sys.dba_obj_audit_opts to assessment_role;
grant select on sys.dba_source to assessment_role;
grant select on sys.dba_tables to assessment_role;
grant select on sys.dba_ts_quotas to assessment_role;
grant select on sys.v_$log to assessment_role;
grant select on sys.dba_registry to assessment_role;
grant select on sys.v_$fixed_table to assessment_role;
grant select on sys.proxy_users to assessment_role;
grant select on sys.dba_policies to assessment_role;
grant select on sys.dba_encrypted_columns to assessment_role;
grant select on sys.dba_indexes to assessment_role;
grant select on sys.dba_ind_partitions to assessment_role;
grant select on sys.dba_tablespaces to assessment_role;
grant select on sys.dba_tab_partitions to assessment_role;
grant select on sys.dba_users_with_defpwd to assessment_role;
grant select on sys.dba_proxies to assessment_role;
grant execute on sys.dbms_crypto to assessment_role;
grant execute on sys.utl_raw to assessment_role;
grant select on sys.dba_constraints to assessment_role;
grant select on sys.DBA_FREE_SPACE to assessment_role;
grant select on sys.DBA_SEGMENTS to assessment_role;
grant select on sys.dba_tab_columns to assessment_role;
grant select on sys.audit$ to assessment_role;
grant select on SYS.default_pwd$ to assessment_role;
grant select on sys.v_$encrypted_tablespaces to assessment_role;
grant select on sys.V_$OPTION to assessment_role;
grant select on sys.v_$tablespace to assessment_role;
grant select on sys.dba_libraries to assessment_role;
grant select on sys.dba_col_privs to assessment_role;
grant select on sys.obj$ to assessment_role;
grant select on sys.objauth$ to assessment_role;
grant select on sys.v_$version to assessment_role;
grant select on sys.audit_unified_policies to assessment_role;
grant select on sys.audit_unified_enabled_policies to assessment_role;
grant select on sys.dba_col_privs to assessment_role;
grant select on sys.table_privilege_map to assessment_role;
grant select on sys.registry$sqlpatch to assessment_role;
grant execute on sys.dbms_qopatch to assessment_role;
grant select on sys.dba_priv_audit_opts to assessment_role;
grant select on sys.dba_obj_audit_opts to assessment_role;
grant select on sys.dba_proxies to assessment_role;
grant select on lbacsys.dba_sa_audit_options to assessment_role;
alter user imperva account lock; 
